system test cunk download and syntax error/56
q-logic/google-resumable-media-python pull request #3
Opened 2019-07-18 12:54 UTC by HemangChothani

issue [56]
- fix syntax error, Due to system tests  run with different versions of python

2019-07-22 21:07 UTC, mf2199 reviewed
Have you tried to run the test after the update? Does it pass?

2019-07-23 04:05 UTC, HemangChothani commented
Yes test_chunk_download  system test pass and it doesn't affect other testcases , though others also fails in master branch adn for that i found separate task.

2019-07-23 04:09 UTC, mf2199 approved these changes

2019-07-31 17:55 UTC, mf2199 requested changes
Please revise your solution as per @tseaver [comments](https://github.com/googleapis/google-resumable-media-python/issues/56).

2019-08-01 07:49 UTC, HemangChothani commented
The problem is from the  back-end side  that header is missing which i mentioned earlier and the solution which @tseaver  is asking for that i have implemented in [PR85](https://github.com/googleapis/google-resumable-media-python/pull/85). May be he also need some clarification on that. response.raw which he wants to implement that i have done in _write_to_stream method  and already tested in system test.

2019-08-05 21:00 UTC, mf2199 commented
Since we have an open public PR, I'm closing this one.

2019-08-05 21:02 UTC, mf2199 commented
Closed by mistake. Reopening.

2019-08-07 16:10 UTC, mf2199 commented
> The problem is from the back-end side that header is missing which i mentioned earlier and the solution which @tseaver is asking for that i have implemented in **`Public Pull Request 85`** .Need some clarification on response.raw which he wants to implement that i have done in _write_to_stream method and already tested in system test.

I'd consult @tseaver about it.

2019-09-11 09:11 UTC, closed without merging